ASide:

  - Room: "d01"

    Holes:

    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    Tweaks:
    - Name: "fgTiles"
      X: 38
      Y: 14
      Update:
        Tile: 0
  - Room: "d02"

    Holes:

    - Side: Down
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 0
      Kind: inout
      ReqIn:
        Or:
        - Dashes: one
          Difficulty: Normal
        - Dashes: two
          Difficulty: Easy
      ReqOut:
        Or:
        - Dashes: two
          Difficulty: Hard
        - Dashes: one
          Difficulty: Master
    - Side: Right
      Idx: 0
      Kind: inout
      ReqIn:
        Or:
        - Dashes: two
          Difficulty: Hard
        - Dashes: one
          Difficulty: Master
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: Normal
        - Dashes: two
          Difficulty: Easy
    Tweaks:
    - Name: "invisibleBarrier"
      X: -8
      Y: 88
      Update:
        Remove: true
  - Room: "d03"

    Holes:
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 0
      Kind: in
      ReqBoth:
        Or:
        - Dashes: one
          Difficulty: Expert
        - Dashes: two
          Difficulty: Hard
    - Side: Right
      Idx: 0
      Kind: out
      ReqBoth:
        Or:
        - Dashes: one
          Difficulty: Expert
        - Dashes: two
          Difficulty: Hard
    Tweaks:
    - Name: "invisibleBarrier"
      X: -8
      Y: 88
      Update:
        Remove: true
  - Room: "d04"

    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    End: true